#!/usr/bin/env bash
#Instal and config haproxy
apt-get update
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get update
apt-get -y install haproxy=2.0.\*
echo "frontend load-banlancer
    bind *:80
    mode http
    default_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo "backend web-backend
    balance roundrobin
    server 1852-web-01 34.73.206.102:80 check
    server 1852-web-02 35.237.118.88:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
