#!/usr/bin/env bash
#Instal and config haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo sed -i '/#EXTRAOPTS="-de -m 16"/a ENABLED=1' /etc/default/haproxy
echo "frontend front
    bind *:80
    mode http
    default_backend back
backend back
    balance roundrobin
    server 1852-web-01 34.73.206.102:80 check
    server 1852-web-02 35.237.118.88:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
